### ISSUE TITLE
Error : Invalid charracter in entity name, when I want to add the plugin

### ISSUE THREAD

**Issue by Stephanux** [xonoxitron/cordova-plugin-hotspot#3]
Hi !

hen i want to use our plugin hotSpotManager, just after to type the commande  :
$ cordova -d plugin add ../cordova-plugin-hotspot

I have this response :

No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "../cordova-plugin-hotspot"
Error: Invalid character in entity name
Line: 8
Column: 26
Char:  
    at error (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/node_modules/sax/lib/sax.js:666:10)
    at strictFail (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/node_modules/sax/lib/sax.js:692:7)
    at SAXParser.write (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/node_modules/sax/lib/sax.js:1491:13)
    at XMLParser.feed (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/lib/elementtree.js:271:10)
    at Object.exports.XML (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/lib/elementtree.js:606:13)
    at Object.parseElementtreeSync (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/src/util/xml-helpers.js:187:38)
    at new PluginInfo (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfo.js:357:37)
    at PluginInfoProvider.get (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfoProvider.js:35:32)
    at /home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:124:47
-------------------------------------------------------------------------------------------------------------------------------------------
with Node.js V: 7.5.0 / npm V : 4.1.2 cordova 6.5.0

In the plugin.ml file à the line 8 and column 26 we can see this :
<description>Cordova pl**u**gin to manage HotSpot/Tethering</description>

Just into the word "plugin" in the description, so i don't understand what is wrong ?
Can you help me ?

**Comment by xonoxitron** [comment]
Try to replace the "/" character form that line and rebuild.

Let me know

Matteo

Matteo Pisani
CTO


On Sat, Oct 14, 2017 at 3:05 PM, Stéphane MASCARON <notifications@github.com

**Comment by Stephanux** [comment]
Thank's fr your response.
Same error with in line 8 into plugin.xml : 
 <description>Cordova plugin to manage HotSpot Tethering</description>

char 26 is 'u' ? i don't understand ?

**Comment by xonoxitron** [comment]
My feeling is that text encoding is different.
Sometime happens with different chartset according to your system.

I suggest you to copy the plugin.xml content into a tool like this:

http://www.online-toolz.com/tools/string-functions.php

Maybe you will discover more

Bests


Matteo Pisani
CTO

**Comment by Stephanux** [comment]
I use find hidden chars to see invisible chars : 
<?xml[Space]version="1.0"[Space]encoding="utf-8"?>[End of Line(LF)]
<plugin[Space]xmlns="http://apache.org/cordova/ns/plugins/1.0"[End of Line(LF)]
[Space][Space][Space][Space][Space][Space][Space][Space]xmlns:android="http://schemas.android.com/apk/res/android"[End of Line(LF)]
[Space][Space][Space][Space][Space][Space][Space][Space]id="cordova-plugin-hotspotmanager"[End of Line(LF)]
[Space][Space][Space][Space][Space][Space][Space][Space]version="1.0.0">[End of Line(LF)]
[End of Line(LF)]
[Space][Space]<name>HotSpotManager</name>[End of Line(LF)]
[Space][Space]<description>Cordova[Space]plugin[Space]to[Space]manage[Space]HotSpot[Space]Tethering</description>[End of Line(LF)]
[Space][Space]<author>Matteo[Space]Pisani[Space]&[Space]Christophe[Space]Dedominici</author>[End of Line(LF)]
[Space][Space]<license>MIT</license>[End of Line(LF)]
[End of Line(LF)]
[Space][Space]<engines>[End of Line(LF)]
[Space][Space][Space][Space]<engine[Space]name="cordova"[Space]version=">=5.0.0"/>[End of Line(LF)]
[Space][Space]</engines>[End of Line(LF)]
[End of Line(LF)]
[Space][Space]<js-module[Space]src="www/hotSpotManager.js"[Space]name="hotSpotManager">[End of Line(LF)]
[Space][Space][Space][Space]<clobbers[Space]target="cordova.plugins.hotSpotManager"[Space]/>[End of Line(LF)]
[Space][Space]</js-module>[End of Line(LF)]
[End of Line(LF)]
[Space][Space]<platform[Space]name="android">[End of Line(LF)]
[Space][Space][Space][Space]<config-file[Space]target="res/xml/config.xml"[Space]parent="/*">[End of Line(LF)]
[Space][Space][Space][Space][Space][Space]<feature[Space]name="HotSpotManager">[End of Line(LF)]
[Space][Space][Space][Space][Space][Space][Space][Space]<param[Space]name="android-package"[Space]value="com.android.plugin.HotSpotManager"[Space]/>[End of Line(LF)]
[Space][Space][Space][Space][Space][Space]</feature>[End of Line(LF)]
[Space][Space][Space][Space]</config-file>[End of Line(LF)]
[Space][Space][Space][Space]<config-file[Space]target="AndroidManifest.xml"[Space]parent="/*">[End of Line(LF)]
[Space][Space][Space][Space][Space][Space]<use-permission[Space]android:name="android.permission.INTERNET"/>[End of Line(LF)]
[Space][Space][Space][Space][Space][Space]<use-permission[Space]android:name="android.permission.ACCESS_NETWORK_STATE"[Space]/>[End of Line(LF)]
[Space][Space][Space][Space][Space][Space]<use-permission[Space]android:name="android.permission.CHANGE_NETWORK_STATE"[Space]/>[End of Line(LF)]
[Space][Space][Space][Space][Space][Space]<use-permission[Space]android:name="android.permission.ACCESS_WIFI_STATE"[Space]/>[End of Line(LF)]
[Space][Space][Space][Space][Space][Space]<use-permission[Space]android:name="android.permission.CHANGE_WIFI_STATE"[Space]/>[End of Line(LF)]
[Space][Space][Space][Space][Space][Space]<use-permission[Space]android:name="android.permission.WRITE_SETTINGS"[Space]/>[End of Line(LF)]
[Space][Space][Space][Space]</config-file>[End of Line(LF)]
[End of Line(LF)]
[Space][Space][Space][Space]<source-file[Space]src="src/android/HotSpotManager.java"[Space]target-dir="src/com/android/plugin/"[Space]/>[End of Line(LF)]
[Space][Space]</platform>[End of Line(LF)]
</plugin>[End of Line(LF)]

i don't see something special which make the error ?
I'm under Linux Ubuntu 16.04 Gnome. Maybe it would be important for encoding characters

i continue to search...

**Comment by xonoxitron** [comment]
Maybe it is the "&" ampersand in the <author> tag

try this:

<?xml version="1.0" encoding="utf-8"?>
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
xmlns:android="http://schemas.android.com/apk/res/android"
id="cordova-plugin-android-hotspotmanager"
version="1.0.0">
<name>HotSpotManager</name>
<description>Cordova plugin to manage HotSpot/Tethering</description>
<author>Matteo Pisani & Christopher Dedominici</author>
<license>MIT</license>
<engines>
<engine name="cordova" version=">=5.0.0"/>
</engines>
<js-module src="www/hotSpotManager.js" name="hotSpotManager">
<clobbers target="cordova.plugins.hotSpotManager" />
</js-module>
<platform name="android">
<config-file target="res/xml/config.xml" parent="/*">
<feature name="HotSpotManager">
<param name="android-package" value="com.android.plugin.HotSpotManager"/>
</feature>
</config-file>
<config-file target="AndroidManifest.xml" parent="/*">
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
<uses-permission android:name="android.permission.WRITE_SETTINGS" />
</config-file>
<source-file src="src/android/HotSpotManager.java" target-dir="
src/com/android/plugin/"/>
</platform>
</plugin>

Matteo Pisani

I use find hidden chars to see invisible chars :

**Comment by Stephanux** [comment]
Sorry don't work

error is this : 
stephane@UX303UB:~/developpement/TestWifi$ cordova -d plugin add ../cordova-plugin-hotspot
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "../cordova-plugin-hotspot"
Error: Invalid character in entity name
Line: 0
Column: 337
Char:  
    at error (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/node_modules/sax/lib/sax.js:666:10)
    at strictFail (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/node_modules/sax/lib/sax.js:692:7)
    at Object.write (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/node_modules/sax/lib/sax.js:1491:13)
    at XMLParser.feed (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/lib/elementtree.js:271:10)
    at Object.exports.XML (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/node_modules/elementtree/lib/elementtree.js:606:13)
    at Object.module.exports.parseElementtreeSync (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/src/util/xml-helpers.js:187:38)
    at new PluginInfo (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfo.js:357:37)
    at PluginInfoProvider.get (/home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfoProvider.js:35:32)
    at /home/stephane/.cvm/6.5.0/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:124:47

**Comment by Stephanux** [comment]
"No scripts found for hook "before_plugin_add"." it is important ?
no script before installation of the plugin ?

**Comment by Stephanux** [comment]
it works !! thank's 
'&' in the authors is in position 337 ;-)
thank's a lot, i continue to test your plugin.

Adichatz ;-)
Stéphane.
